AWSTemplateFormatVersion: '2010-09-09'
Description: Lambda with spring boot.
Outputs:
  LambdaSpringBootApi:
    Description: URL for application
    Export:
      Name: LambdaSpringBootApi
    Value:
      Fn::Sub: https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Stage/languages
Resources:
  LambdaSpringBootFunction:
    Properties:
      CodeUri: s3://acloudguru-polly-mp3s2027/e43d6243120666b274f61724725870d7
      Events:
        GetResource:
          Properties:
            Method: any
            Path: /{proxy+}
          Type: Api
      Handler: com.keyholesoftware.lambda.LambdaHandler::handleRequest
      MemorySize: 1512
      Policies: AWSLambdaBasicExecutionRole
      Runtime: java8
      Timeout: 60
    Type: AWS::Serverless::Function
Transform: AWS::Serverless-2016-10-31
